### ISSUE TITLE
Orthography profile?

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/starostinkaren#2]
Do we know if the GLD uses a consistent orthography?

**Comment by tresoldi** [comment]
I would expect so, especially for this dataset. A quick look at the forms seems to confirm it. Maybe I should give it a try, and @LinguList refines/confirms later?

**Comment by SimonGreenhill** [comment]
yes please! :) I'm hoping the profile will hold across all the GLD datasets too

**Comment by tresoldi** [comment]
Sure. I'll wait for the PR to be merged.

**Comment by LinguList** [comment]
Yes, in theory very consistent. I made an initial profile for
Hmong-Mien, the other dataset, but you cannot use them always, as they
have things like prenasal clusters, but in theory, there should be a
big-big profile apt for all GLD. My starostinhmongmien profile is a
first example.

**Comment by LinguList** [comment]
Yes, see my other answer, @tresoldi, this was one of the first profiles
we made.

**Comment by tresoldi** [comment]
Great, I'll use it as a reference.

**Comment by LinguList** [comment]
BTW, check here for their specification:
http://starling.rinet.ru/new100/UTS.htm

**Comment by SimonGreenhill** [comment]
this is done, right?
