### ISSUE TITLE
update contributors, add how to cite statement, and sources

### ISSUE THREAD

**Issue by LinguList** [lexibank/starostinkaren#4]
> Starostin, George S. (2017): Annotated Swadesh Wordlists for the Karen Group. Moscow: The Global Lexicostatistical Database.

**Comment by chrzyki** [comment]
I've updated the citation information. What should the contributors update look like?

**Comment by LinguList** [comment]
Please check on the tob website, who compiled the list. I made the
orthography profiles and the like, and also the general TOB provider
stuff. Please add the person from ToB listed as the compiler as main
author, myself and others involved as "other" for zenodo.

**Comment by chrzyki** [comment]
Will do, thanks.
