### ISSUE TITLE
Missing raw data

### ISSUE THREAD

**Issue by FredericBlum** [lexibank/starostinkaren#6]
@xrotwang @chrzyki This repo has only 18 of 110 concepts from the raw data online. Do you know if somebody else worked on this? Or is this dataset something we should ignore right now?

**Comment by xrotwang** [comment]
With "online" you mean at lexibank.clld.org? Isn't inclusion in lexibank-analysed based on some coverage thresholds? Maybe these were not met for the other concepts?

**Comment by xrotwang** [comment]
Ah, I see. Only 18 make it into the CLDF dataset.

**Comment by xrotwang** [comment]
Looking at https://github.com/lexibank/starostinkaren/blob/master/raw/output.csv it seems there are only 18 concepts - just a lot of synonyms. Don't know whether that's correct, or fetching the raw data already went wrong.

**Comment by FredericBlum** [comment]
With online I meant the source mentioned in the Readme: https://starling.rinet.ru/cgi-bin/response.cgi?root=new100&morpho=0&basename=new100%5Cstb%5Ckrn&limit=-1

**Comment by xrotwang** [comment]
The download behaviour seems correct, at least in light of the specified page range, see
https://github.com/lexibank/starostinkaren/blob/2aacea932e1a53511582288b71273ec053ed6482/lexibank_starostinkaren.py#L8

Whether that's deliberate or simply a copy&paste error, not adapting the defaults, I don't know. @LinguList ideas?

**Comment by LinguList** [comment]
Is there a problem with the download? Sorry I did not follow this. The starostinkaren is a project I never followed up further. It was only me working on it.

**Comment by LinguList** [comment]
I think I should either look into this when having some quiet time during the next days, or we leave it at the side for now.

**Comment by xrotwang** [comment]
> I think I should either look into this when having some quiet time during the next days, or we leave it at the side for now.

As far as I can tell, we could easily expand coverage by simply adjusting the `pages = ...` setting.

**Comment by FredericBlum** [comment]
Doesn't really work, the output.csv does not get updated when modifying the pages variable. So I guess we do not add this dataset, considering the amount of work we'd need to put in. It's also less than 200 concepts, so not really interesting for CLICS etc.

**Comment by LinguList** [comment]
I have scheduled to check on Sunday. I will tell you if I can fix it. The crawler should work for virtually all GLD datasets, so one could add more, and the orthoprofile is also pretty unified. But I will make it dependent on whether I find time.

**Comment by LinguList** [comment]
@xrotwang was right, if you define pages as 10, it downloads everything.

**Comment by LinguList** [comment]
I by then wanted to set up a general WF to get all data from GLD in a regular manner.

**Comment by LinguList** [comment]
There's a little bit of work to do, however. I just checked, and we have some 39 BIPA errors.

**Comment by LinguList** [comment]
But I got it now.

**Comment by LinguList** [comment]
It is at 0 errors now. we could add it, also to show that we are keen on supporting datasets like GLD in the future.

**Comment by LinguList** [comment]
I'll close here and leave this for inspection (there are certainly errors in my orthography conversion, I dropped tone marks, but it is probably okay enough to be included).
